name: Remote Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build Go binary for Linux
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o ./target/ocha_bot

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop bot services on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            sudo systemctl stop ocha-bot.service || true
            sudo systemctl stop mine-sweeper-bot.service || true

      - name: Remove old binary on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            rm -f ~/ocha_bot

      - name: Upload new binary to remote server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./target/ocha_bot ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/ocha_bot

      - name: Start bot services on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            sudo systemctl start ocha-bot.service
            sudo systemctl start mine-sweeper-bot.service

      - name: Verify services are running
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            systemctl is-active --quiet ocha-bot.service && echo 'ocha-bot is running' || echo 'ocha-bot failed to start'
            systemctl is-active --quiet mine-sweeper-bot.service && echo 'mine-sweeper-bot is running' || echo 'mine-sweeper-bot failed to start'
